# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_price',
        ),
    ]
